version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=password
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.0
    environment:
      - ELASTICSEARCH_HOST=https://elasticsearch:9200
      - ELASTICSEARCH_USER=admin
      - ELASTICSEARCH_PASSWORD=password
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none # Skips SSL verification for simplicity
    ports:
      - "5044:5044" # Logstash Beats input
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      # - ./logstash/config:/usr/share/logstash/pipeline
    depends_on: 
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.0
    user: root
    volumes:
      - /c/logs:/mnt/logs:ro
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
    command: bash -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e"

volumes:
  esdata: